[package]
name = "ayanami_rei"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
log = "0.4"
env_logger = "0.10"